[package]
name = "blog-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
dotenv = "0.15"
sqlx = { version = "0.5", features = ["runtime-actix-native-tls", "postgres"] }
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "7.2"